---
title: "Data Acquisition"
author: "Corinna Boenke"
---

# Challenge 2

## Load librarys
```{r}
library(conflicted)
library(dplyr)
library(tidyverse) 
library(rvest)    
library(xopen) 
library(httr)
library(glue)      
library(stringi)
library(jsonlite)
library(magrittr)


```
## Part 1

### API Data
```{r}
conflicts_prefer(jsonlite::fromJSON)
res = GET("https://api.open-meteo.com/v1/forecast?latitude=53.55&longitude=9.99&daily=temperature_2m_max,temperature_2m_min,uv_index_max,precipitation_sum&timezone=auto")
data = fromJSON(rawToChar(res$content))
names(data)
data$daily
```
### Table for Weather Forecast
```{r}

Weather_list <- fromJSON(rawToChar(res$content), flatten = TRUE)
df <- Weather_list$daily
class(df)
head(df)
Weather_forecast = as.data.frame(df)
Weather_forecast


```
## Part 2

### Bike Family

```{r}
#3.2
url_home <- "https://www.rosebikes.com/bikes"
bikes_home <- url_home %>%
  read_html()

bike_family_tbl <- bikes_home %>%
  html_nodes(css = ".catalog-navigation__link")%>%
  html_attr('title') %>%
  discard(.p = ~stringr::str_detect(.x, "Bikes with short delivery times"))%>%
  enframe(name = "position", value = "family_class") %>%
  mutate(family_id = str_glue("#{family_class}"))%>%
  mutate(url = glue("https://www.rosebikes.com/bikes/{family_class}"))

bike_family_tbl
```

### Get Data
```{r}
bike_category_url <- bike_family_tbl$url[1]
html_bike_category <- read_html(bike_category_url)

get_bike_data <- function(url){
 
  html_bike_category <- read_html(url)
  bike_category_url <- bike_family_tbl$url[1]
  html_bike_category <- read_html(bike_category_url)
 
  #urls
  bike_url_tbl <- html_bike_category %>%
    html_nodes(css =".catalog-category-bikes__button") %>%
    html_attr("href") %>%
    str_remove(pattern = "\\?.*") %>%
    enframe(name = "position",value = "part_url") %>%
    mutate(url = glue("https://www.rosebikes.com{part_url}"))
  bike_url_tbl
 
  #Bike Names
  bike_name_tbl <- html_bike_category %>%
    html_nodes(".basic-headline__title") %>%
    html_text() %>%
    str_remove(pattern = "\\n") %>%
    str_remove(pattern = "\"") %>%
    enframe(name = "position", value = "Name")
  bike_name_tbl
 
  #descriptions
  bike_desc_tbl <- html_bike_category %>%
    html_nodes(".catalog-category-bikes__content-subtitle") %>%
    html_text() %>%
    str_remove(pattern = "\\n") %>%
    str_remove(pattern = "\"") %>%
    enframe(name = "position", value = "Description")
 
  #prices
  bike_price_tbl <- html_bike_category %>%
    html_nodes(".catalog-category-bikes__price-title") %>%
    html_text() %>%
    str_remove(pattern = "\\n") %>%
    str_remove(pattern = "\"") %>%
    enframe(name = "position", value = "Price") %>%
    left_join(bike_desc_tbl, by = character()) %>%
    left_join(bike_name_tbl, by = character()) %>%
    left_join(bike_url_tbl, by = character()) %>%
    select(Name, url, Description, Price) %>%
    as_tibble()
  bike_price_tbl
}
```
### Loop
```{r}
rose_bike_data_tbl <- tibble()
for(i in seq_along(bike_family_tbl$url)){
  bike_category_url <- bike_family_tbl$url[i]
  rose_bike_data_tbl <- bind_rows(rose_bike_data_tbl, get_bike_data(bike_category_url))
  Sys.sleep(5)
  print(i)
}
```
### Table
```{r}
print(rose_bike_data_tbl, n=20)
glimpse(rose_bike_data_tbl)
rose_bike_data_tbl


```     
      



